jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        ajax_auth_provider:
            id: ajax_auth.user.provider
        # in_memory:
        #     memory:
        #         users:
        #             user:  { password: userpass, roles: [ 'ROLE_USER' ] }
        #             admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        # secured_area:
        #     pattern: ^/
        #     anonymous: ~
        #     form_login:
        #         check_path: /login_check
        #         login_path: _ajax_auth_login
        #         use_referer: true
        #     logout:
        #         path:   _demo_logout
        #         target: _demo
        ajax_secured:
            pattern: ^/
            ajax-auth:
                check_path: /login_check
                login_path: /login
                remember_me: true
                provider: ajax_auth_provider
            remember_me:
                key:      divine_office_hub_1234567
                lifetime: 31536000
                path: /
                domain: ~
            # anonymous: ~
            # ajax:      true
            # form_login:
            #     check_path: _ajax_auth_check
            #     login_path: _ajax_auth_login
            # logout:
            #     path:   _demo_logout
            #     target: _demo

    access_control:
        - { path: ^/account, roles: ROLE_USER }
