jms_security_extra:
    secure_all_services: false
    expressions: true

###
ajax_auth:
    default_redirect_path     : bla
    always_use_default_path   : false
    user_registration_handler : smth_test.register.handler
###

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Smth\TestBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_providers:
            chain: {providers: [in_memory_provider, entity_provider]}
        in_memory_provider:
            memory:
                users:
                    admin: { password: testpass123!, roles: [ 'ROLE_ADMIN' ] }
        entity_provider:
            entity: {class: SmthTestBundle:User, property: username}

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern: ~
            anonymous: ~
            form_login:
                check_path: _login_check
                login_path: _login
                use_referer: true
                remember_me: true
                success_handler: smth_ajax_auth.handler
                failure_handler: smth_ajax_auth.handler
            remember_me:
                key: %secret%
                lifetime: 31536000
                path: /
                domain: ~
                always_remember_me: false
            logout:
                path:   _demo_logout
                target: _demo

    access_control:
        - { path: ^/account, roles: ROLE_USER }
