jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Smth\AjaxAuthBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_providers:
            chain: {providers: [in_memory_provider, entity_provider]}
        in_memory_provider:
            memory:
                users:
                    admin: { password: testpass123!, roles: [ 'ROLE_ADMIN' ] }
        entity_provider:
            entity: {class: AjaxAuthBundle:User, property: username}

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern: ~
            anonymous: ~
            form_login:
                check_path: /login_check
                login_path: _ajax_auth_login
                use_referer: true
            logout:
                path:   _demo_logout
                target: _demo
    access_control:
        - { path: ^/account, roles: ROLE_USER }
