// Generated by CoffeeScript 1.6.2
(function() {
  var AjaxAuthForm,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  AjaxAuthForm = (function() {
    function AjaxAuthForm(form) {
      this.form = form;
      this._ajax = __bind(this._ajax, this);
      this._onSubmit = __bind(this._onSubmit, this);
      this._beforeSubmit = __bind(this._beforeSubmit, this);
      console.log('form:', this.form);
      this.username = this.form.find('input[name=_username]');
      this.password = this.form.find('input[name=_password]');
      this.form.bind('submit', this._onSubmit);
    }

    AjaxAuthForm.prototype._beforeSubmit = function(_callback) {
      return _callback.apply(this);
    };

    AjaxAuthForm.prototype._onSubmit = function(e) {
      console.log(arguments);
      e.preventDefault();
      return this._beforeSubmit(this._ajax);
    };

    AjaxAuthForm.prototype._ajax = function() {
      var _this = this;

      return $.ajax({
        url: '/app_dev.php/login_check',
        type: 'POST',
        dataType: 'json',
        data: {
          _username: this.username.val(),
          _password: this.password.val(),
          _remember_me: true
        },
        success: function(response) {
          return console.log(arguments);
        },
        error: function(response) {
          return console.log(arguments);
        }
      });
    };

    return AjaxAuthForm;

  })();

}).call(this);
