parameters:
    smth_ajax_auth.handler.class: Smth\AjaxAuthBundle\Security\Authentication\AuthenticationHandler
    smth.security.authentication.class: Smth\AjaxAuthBundle\Security\Authentication\UserAuthentication
    smth.security.registration.class: Smth\AjaxAuthBundle\Security\Authentication\UserRegistrationHandler
    smth_ajax_auth.facebook_connector.class: Smth\AjaxAuthBundle\Connector\FacebookConnector
    smth_ajax_auth.google_connector.class: Smth\AjaxAuthBundle\Connector\GoogleConnector
services:
# Authentication Success Handler
    smth_ajax_auth.handler:
        class:  %smth_ajax_auth.handler.class%
        arguments:  
            router                  : @router
            default_redirect_path   : ''
            always_use_default_path : ''
        tags:
            - { name: 'monolog.logger', channel: 'security' }
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLoginEvent }
# User Registration Handler
    ajax_auth.user_registration.handler:
        abstract: true
        class: %smth.security.registration.class%
        calls:
            - [setAuthService, [@smth.security.authentication]]
# Twig Extension
    extension.twig.ajax_auth:
        class: Smth\AjaxAuthBundle\Extension\AjaxAuthTwigExtension
        arguments: [@router]
        tags:
            - { name: twig.extension }
# WebServices Connectors
    smth_ajax_auth.connector.facebook:
        class: %smth_ajax_auth.facebook_connector.class%
    smth_ajax_auth.connector.google:
        class: %smth_ajax_auth.google_connector.class%
# Authentication Helper
    smth.security.authentication:
        class: %smth.security.authentication.class%
        calls:
            - [setContainer, [@service_container]]